### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by nayuta723** [nayuta-ai/invertible-resnet-pytorch#5]
## Background
My research needs to factorize the intermediate layer using the invertible structure such as a flow-based model. In invertible-resnet, it can have an invertible structure and perform high classification accuracy. So, I want to use the invertible-resnet in my research. There is some GitHub repository on invertible-resnet, but there was an error due to a dependency module. Since it was implemented three years ago, I also could not reproduce the implementation. My goal is to conduct a full scratch Implementation of an invertible-resnet.

## Goal
This issue will be closed when I finish implementing the invertible-resnet.
I will carry out some experiments on an invertible-resnet.

### Overview
I will set up the docker environment (#1 docker), comet-ml (#2 comet-ml), GitHub actions (#3 Github).
I will implement the invertible-resnet such as parsing args, getting the dataset, getting the model, etc.
### To do
- [x] Set up Docker (#1)
- [x] Set up comet-ml (#2)
- [x] Set up GitHub (#3)
- [x] Implement argparse (#4)
- [ ] Implement get_dataloader (#7)
- [ ] Implement get_model (#8 )
- [ ] Implement the train function(#9 )
- [ ] Install rubber data

## Frequency
Every Day

## Deadline
2022/8

## References
https://github.com/jhjacobsen/invertible-resnet

## Notes
None

**Comment by nayuta723** [comment]
## Working Time
3.5h

## Supplement for the task
I modified #7 and implement #8 and the train function according to [this](https://github.com/jhjacobsen/invertible-resnet). I didn't clean #8 and the train function because there are many lines, and I focused on implementing the invertible resnet until 8/25.
